# Generated by Django 4.1.4 on 2022-12-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_tutormodule_changed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorModule',
        ),
    ]
