# Generated by Django 4.1.4 on 2022-12-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tutormodule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorModule',
        ),
    ]
