# Generated by Django 4.1.4 on 2022-12-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_tutors', '0003_tutormodule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorModule',
        ),
    ]
