# Generated by Django 4.1.4 on 2022-12-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_tutors', '0005_tutormodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.AlterModelOptions(
            name='abouttutor',
            options={'verbose_name': 'Моя анкета'},
        ),
        migrations.RemoveField(
            model_name='abouttutor',
            name='language',
        ),
        migrations.AddField(
            model_name='abouttutor',
            name='language',
            field=models.ManyToManyField(related_name='languages', to='cabinet_tutors.language', verbose_name='Язык преподавания'),
        ),
    ]
