# Generated by Django 4.1.4 on 2022-12-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_tutors', '0007_tutoreducationanddiplomas_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutormodule',
            name='education_and_diplomas',
        ),
        migrations.RemoveField(
            model_name='tutormodule',
            name='study_formats',
        ),
        migrations.RemoveField(
            model_name='tutormodule',
            name='subjects_and_costs',
        ),
        migrations.AddField(
            model_name='tutormodule',
            name='education_and_diplomas',
            field=models.ManyToManyField(blank=True, null=True, related_name='education_and_costs', to='cabinet_tutors.tutoreducationanddiplomas', verbose_name='Образование и дипломы'),
        ),
        migrations.AddField(
            model_name='tutormodule',
            name='study_formats',
            field=models.ManyToManyField(blank=True, null=True, related_name='study_formats', to='cabinet_tutors.studyformats', verbose_name='Формат обучения'),
        ),
        migrations.AddField(
            model_name='tutormodule',
            name='subjects_and_costs',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects_and_costs', to='cabinet_tutors.subjectsandcosts', verbose_name='Предметы и стоимость'),
        ),
    ]
